### ISSUE TITLE
pip install fails on MacOS

### ISSUE THREAD

**Issue by marcpaga** [epi2me-labs/modbam2bed#33]
I have been trying to install modbampy via pip on MacOS but it fails.

I have tried on python 3.7, 3.8 and 3.9; haven't managed to get it to work in any. All this on a clean virtual environment.

Here's the output when running `pip install modbampy==0.6.3`

```
Collecting modbampy==0.6.3
  Using cached modbampy-0.6.3.tar.gz (987 kB)
  Preparing metadata (setup.py) ... done
Collecting cffi==1.15.0
  Using cached cffi-1.15.0-cp37-cp37m-macosx_10_9_x86_64.whl (178 kB)
Collecting numpy
  Using cached numpy-1.21.6-cp37-cp37m-macosx_10_9_x86_64.whl (16.9 MB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Installing collected packages: pycparser, numpy, cffi, modbampy
  DEPRECATION: modbampy is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for modbampy ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for modbampy did not run successfully.
  │ exit code: 1
  ╰─> [63 lines of output]
      WITHDEFLATE: None
      /Users/mpages/Documents/sturgeon2/venv/lib/python3.7/site-packages/cffi/cparser.py:154: UserWarning: String literal found in cdef() or type source. String literals are ignored here, but you should remove them anyway because some character sequences confuse pre-parsing.
        warnings.warn("String literal found in cdef() or type source. "
      running install
      running build
      running build_py
      creating build
      creating build/lib.macosx-12-x86_64-3.7
      creating build/lib.macosx-12-x86_64-3.7/modbampy
      copying modbampy/__init__.py -> build/lib.macosx-12-x86_64-3.7/modbampy
      running build_ext
      generating cffi module 'build/temp.macosx-12-x86_64-3.7/libmodbampy.c'
      creating build/temp.macosx-12-x86_64-3.7
      Compiling htslib using Makefile
      Compiling libhts.a
      cd htslib/ \
                  && autoreconf -i \
                  && autoheader \
                  && autoconf \
                  && CFLAGS="-fpic -msse3 -O3 -std=c99 " ./configure  \
                  && make -j 4
      /bin/sh: autoreconf: command not found
      make: *** [htslib/libhts.a] Error 127
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/pp/5r_lsyld0s5707v7k1b885h40000gp/T/pip-install-pzfe3igs/modbampy_71a11a4180f54f86b30c846047adfb7f/setup.py", line 89, in <module>
          scripts=[]
        File "/Users/mpages/Documents/sturgeon2/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/Cellar/python@3.7/3.7.15/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/local/Cellar/python@3.7/3.7.15/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/local/Cellar/python@3.7/3.7.15/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Users/mpages/Documents/sturgeon2/venv/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/usr/local/Cellar/python@3.7/3.7.15/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/install.py", line 545, in run
          self.run_command('build')
        File "/usr/local/Cellar/python@3.7/3.7.15/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/Cellar/python@3.7/3.7.15/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/local/Cellar/python@3.7/3.7.15/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/local/Cellar/python@3.7/3.7.15/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/Cellar/python@3.7/3.7.15/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Users/mpages/Documents/sturgeon2/venv/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 144, in run
          base_class.run(self)
        File "/private/var/folders/pp/5r_lsyld0s5707v7k1b885h40000gp/T/pip-install-pzfe3igs/modbampy_71a11a4180f54f86b30c846047adfb7f/setup.py", line 57, in run
          self.execute(compile_hts, [], 'Compiling htslib using Makefile')
        File "/usr/local/Cellar/python@3.7/3.7.15/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 335, in execute
          util.execute(func, args, msg, dry_run=self.dry_run)
        File "/usr/local/Cellar/python@3.7/3.7.15/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/util.py", line 291, in execute
          func(*args)
        File "/private/var/folders/pp/5r_lsyld0s5707v7k1b885h40000gp/T/pip-install-pzfe3igs/modbampy_71a11a4180f54f86b30c846047adfb7f/setup.py", line 55, in compile_hts
          subprocess.check_call(['make', os.path.join('htslib', 'libhts.a'), 'pymod.a'])
        File "/usr/local/Cellar/python@3.7/3.7.15/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 363, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['make', 'htslib/libhts.a', 'pymod.a']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> modbampy

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

Running `pip install modbampy==0.6.3 --use-pep517` as pip suggests successfully install modbampy, but then within python import fails.

```
Python 3.7.15 (default, Oct 11 2022, 13:45:04) 
[Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import modbampy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mpages/Documents/sturgeon2/venv/lib/python3.7/site-packages/modbampy/__init__.py", line 8, in <module>
    import libmodbampy
ModuleNotFoundError: No module named 'libmodbampy'
```

Any ideas on how to solve this?

**Comment by cjw85** [comment]
Hi @marcpaga,

The Python package could do with a precompiled package for macOS: currently pip will download the source package and try to compile the code. You will therefore need to install build tools on your mac in order to install the package. It looks like you're already using homebrew, so I would suggest using that to install them.

**Comment by marcpaga** [comment]
@cjw85 Thanks for the quick response. I am a bit lost here, do you know which build tools should I install?

**Comment by marcpaga** [comment]
For anyone running into the same issue, running `brew install automake` fixed the issue, and was able to compile the package. This worked for python 3.7, but fails for 3.9.
